### ISSUE TITLE
Adding HtmxUtils for better reference in Templates

### ISSUE THREAD

**Issue by tschuehly** [wimdeblauwe/htmx-spring-boot#106]
In every project I'm doing I create a HtmxUtil class, I think this improves template readability, and could start establishing good practices.

For example having a URI method to put variables into a constant: 

```
  public static String URI(String uriTemplate, Object... variables) {
    return new UriTemplate(uriTemplate).expand(variables).toString();
  }
```
and then in the controller
```
  public static final String GET_EDIT_USER_MODAL = "/save-user/modal/{uuid}";

  @GetMapping(GET_EDIT_USER_MODAL)
  public ViewContext editUserModal(@PathVariable UUID uuid) {
    return editUserComponent.render(uuid);
  }
```
then in the template
```
        <button hx-get="${URI(GET_EDIT_USER_MODAL,uuid)}"
                hx-target="#${MODAL_CONTAINER_ID}">
            <img src="/edit.svg">
        </button>
```

Here's an example:
https://github.com/tschuehly/htmx-spring-workshop/blob/lab-4/src/main/java/de/tschuehly/easy/spring/auth/htmx/HtmxUtil.java

**Comment by wimdeblauwe** [comment]
I personally don't really like having constants for the URL paths. I don't feel it improves the readability of the code as the function of a controller method is mapping a URL to a method, so I like to have my URL close to my method. Some might call it locality of behaviour ;-)

But if others feel this is useful, we could add this.

**Comment by tschuehly** [comment]
In a big project, it really helps finding where Controller Endpoints are used. Especially as you can browse around with CTRL + B between your templates and your Controllers in IntelliJ.

**Comment by checketts** [comment]
The constants are separate from the HtmxUtils discussion. I would expose the utils class as a bean then reference it via `@util.uri()` syntax. (That references Spring beans)

However, I haven't found a consistent use for it. So I would be interested to see the proposed methods.

**Comment by tschuehly** [comment]
> The constants are separate from the HtmxUtils discussion. I would expose the utils class as a bean then reference it via `@util.uri()` syntax. (That references Spring beans)

Once again, I would stay with a complete static Util Class as we can use it with all template langauges

> However, I haven't found a consistent use for it. So I would be interested to see the proposed methods.
I will clean one up and post it here,

**Comment by landsman** [comment]
I would love to see this utils, it make sense to me.

**Comment by xhaggi** [comment]
@wimdeblauwe IMO this is not a htmx-specific issue. I use a similar approach in some projects, but I see no compelling reason to include it in this library. Should we close this issue with `Won't fix`?

**Comment by wimdeblauwe** [comment]
I tend to agree with @xhaggi on this.
