### ISSUE TITLE
Remove commented out spring-asciidoctor-backends in pom.xml?

### ISSUE THREAD

**Issue by Riggs333** [wimdeblauwe/htmx-spring-boot#112]
I noticed this commented out snippet in the pom.xml about [spring-asciidoctor-backends](https://github.com/spring-io/spring-asciidoctor-backends):

https://github.com/wimdeblauwe/htmx-spring-boot/blob/46c13f1f4f5e153dcf5c311cfa293e1e8460812a/pom.xml#L151-L160

(I don't know yet what was planned to do with it (as I haven't found any asciidoc-files in this repository), maybe you wanted to create some documentation in spring style?)

Nevertheless, it looks like [the artifact was published in January 2023](https://github.com/spring-io/spring-asciidoctor-backends/issues/72) and is [available in Maven Central](https://central.sonatype.com/artifact/io.spring.asciidoctor.backends/spring-asciidoctor-backends).

If I misunderstood something and you want to keep the code in the `pom.xml` then feel free to close this issue.

**Comment by wimdeblauwe** [comment]
It can be removed indeed. Feel free to open a PR for it.
