### ISSUE TITLE
Spring Security filter chain config

### ISSUE THREAD

**Issue by taypo** [wimdeblauwe/htmx-spring-boot#115]
The following piece of code, when added breaks my app doing oauth2 login. Is there possibly a way its added to the existing config that's auto configured from application.yml.

```
@Bean
public SecurityFilterChain filterChain(HttpSecurity http)throws Exception{
    // probably some other configurations here

    var entryPoint = new HxRefreshHeaderAuthenticationEntryPoint();
    var requestMatcher = new RequestHeaderRequestMatcher("HX-Request");
    http.exceptionHandling(exception ->
        exception.defaultAuthenticationEntryPointFor(entryPoint, requestMatcher));
    return http.build();
}
```

For example, when I prepend the code with 

```
http.authorizeHttpRequests { registry -> registry.requestMatchers("/**").authenticated() }
			.oauth2Login(Customizer.withDefaults())
```

its starts to work again, but I'm not really sure if I'm still overriding some other defaults. (sorry about the kotlin syntax)

**Comment by wimdeblauwe** [comment]
Your question is unclear to me. Do you have a small reproducer project I can take a look at?

**Comment by wimdeblauwe** [comment]
Closing issue because of lacking info.
