### ISSUE TITLE
Annotations missing

### ISSUE THREAD

**Issue by juanjonavarro** [wimdeblauwe/htmx-spring-boot#122]
In the README file, it states:

```
The following annotations are currently supported:

@HxLocation
@HxPushUrl
@HxRedirect
@HxRefresh
@HxReplaceUrl
@HxReselect
@HxReswap
@HxRetarget
@HxTrigger
@HxTriggerAfterSettle
@HxTriggerAfterSwap
```

However, these annotations do not seem to be available in version 3.3.0.

Am I missing something?

**Comment by xhaggi** [comment]
These changes are part of the next version 3.4.0. You must pick the README.md that corresponds to the correct version.

https://github.com/wimdeblauwe/htmx-spring-boot/blob/3.3.0/README.md

**Comment by wimdeblauwe** [comment]
It was a good reminder that I still needed to release 3.4.0 which I just did now: https://github.com/wimdeblauwe/htmx-spring-boot/releases/tag/3.4.0
