### ISSUE TITLE
Use Fragment Rendering in Spring Framework 6.2

### ISSUE THREAD

**Issue by rstoyanchev** [wimdeblauwe/htmx-spring-boot#148]
Spring Framework 6.2 added [fragment rendering support](https://docs.spring.io/spring-framework/reference/web/webmvc-view/mvc-fragments.html) for both Spring MVC and Spring WebFlux. This includes rendering multiple model and view fragments, as well as streaming model and view fragments over SSE, and eliminates the limitation [mentioned here](https://github.com/wimdeblauwe/htmx-spring-boot/tree/feature/gh-125_hx-on-support?tab=readme-ov-file#html-fragments). The implementation can be simplified, removing the need for the workarounds currently in place.

/cc @odrotbohm who experimented with the changes and has a prototype to share.

**Comment by xhaggi** [comment]
We are aware of this and will adapt the code in the upcoming version 4.0, in which we plan to upgrade to Spring Boot 3.4.0.

**Comment by rstoyanchev** [comment]
Good to know, and I did see #147, but didn't see a mention there.

**Comment by xhaggi** [comment]
>Good to know, and I did see https://github.com/wimdeblauwe/htmx-spring-boot/issues/147, but didn't see a mention there.

Had it in mind, but not as a todo in #147. Now it's there.
