### ISSUE TITLE
Queston: Triggers HtmxResponse in 4.0.0?

### ISSUE THREAD

**Issue by resmo** [wimdeblauwe/htmx-spring-boot#155]
Hi

I make use of `triggers` in HtmxResponse and wonder how this would be possible in 4.0.0 with HtmxResponse gone? Thanks in advance.

```java
@HxRequest(boosted = false)
@PostMapping("")
public HtmxResponse hxSave(
        @Valid
        @ModelAttribute("address") AddressDto addressDto,
        BindingResult result,
        Model model
) {
    if (result.hasErrors()) {
        model.addAttribute("address", addressDto);
        Iterable<Person> persons = personService.findAll();
        model.addAttribute("persons", persons);
        return HtmxResponse.builder()
                .view("address/partial/dialogs :: form-dialog")
                .build();
    } else {
        try {
            Address address = addressService.save(addressDto);
            model.addAttribute("success", address);
            return HtmxResponse.builder()
                    .trigger("addressChanged")
                    .view("address/partial/dialogs :: form-dialog")
                    .view("fragments/message :: saved")
                    .build();

        } catch (Exception ex) {
            model.addAttribute("error", ex.getLocalizedMessage());
            model.addAttribute("address", addressDto);
            return HtmxResponse.builder()
                    .view("address/partial/dialogs :: form-dialog")
                    .build();
        }
    }
}
```

**Comment by resmo** [comment]
So, what should be done to add the trigger header to the fragments rendering return?

```java
@HxRequest(boosted = false)
@PostMapping("/bla")
public View example(
        HtmxResponse htmxResponse,
        Model model
) {
        htmxResponse.addTrigger("testTrigger");

        return FragmentsRendering
                .with("example")
                .build();
}
```

**Comment by checketts** [comment]
@resmo Your sample should work. Are you not seeing the trigger header?

**Comment by xhaggi** [comment]
@resmo there is no need to return `FragmentsRendering` if you only want to return a single view. Simply return the view as a string.

**Comment by saipanman95** [comment]
I am running into a similar issue working with logic to set a retarget and a trigger.  Both are not showing up in network response.   
`@PutMapping(value = "/person/{personId}/email/update")
    @HxRequest(boosted = false)
    public View updateEmail(@ModelAttribute Email email,
                            @PathVariable("personId") Long personId,
                            HtmxResponse htmxResponse,
                            Model model) {

        Person person = personService.getPersonById(personId);

        boolean emailExists = emailService.emailExistsForPerson(email.getEmailAddress(), person);

        if(emailExists){
            String alertMessage = "The email address " + email.getEmailAddress() + " already exists for this person.";
            String alertLevel = "danger";

            // Add the alert message and level to the model
            model.addAttribute("alertMessage", alertMessage);
            model.addAttribute("alertLevel", alertLevel);

            htmxResponse.setRetarget("#email-alert-message");
         
            return FragmentsRendering
                    .with("fragments/alert-message :: alert-message").build();
        } else {
            emailService.saveOrUpdateEmail(person, email);
            model.addAttribute("emails", person.getEmails());
            model.addAttribute("personId", personId);

            String message = email.getEmailAddress() + " was updated";
            String jsonTrigger = "{\"emailUpdated\":{\"level\":\"info\",\"target\":\"#email-alert-message\", \"message\":\"" + message + "\"}}";

            htmxResponse.addTrigger(jsonTrigger);

            return FragmentsRendering.with("person/emails-info :: emails-info").build();
        }
    }`

So I have tried it without the FragmentRendering as well used Strings to with the path but it appears the header responses are not populating.

**Comment by xhaggi** [comment]
@wimdeblauwe I have done some tests and can confirm that the current versions 3.6.x and 4.0.x are broken, although the tests do not fail.

This was introduced by https://github.com/wimdeblauwe/htmx-spring-boot/commit/9cc73313f8e62e083b4ef3194575982e118b0876 because I moved the setting of the response headers from `HtmxHandlerInterceptor#postHandle` to `HtmxHandlerInterceptor#afterCompletion`, but setting the response headers in `afterCompletion` seems to happen too late in the lifecycle of the request. Reverting this change fixes the problem, but the `ExceptionHandler` tests in `HtmxHandlerMethodTest` fail afterwards. Finally I got it and fixed it with #157.

**Comment by wimdeblauwe** [comment]
Versions [3.6.3](https://github.com/wimdeblauwe/htmx-spring-boot/releases/tag/3.6.3) and [4.0.1](https://github.com/wimdeblauwe/htmx-spring-boot/releases/tag/4.0.1) are now released with a fix for this issue. Sorry for the inconvenience!

**Comment by saipanman95** [comment]
Hi @wimdeblauwe, sorry man.  I hope I am missing something in my code but this does not seem to be working still.  Let me give you a code fragment I am using to test this:
```java
@PostMapping("/student/update/{studentId}")
    @HxRequest(boosted = false)
    public String updateStudent(@PathVariable("studentId") Long studentId,
                                @ModelAttribute Student student, Model model,
                                HtmxResponse htmxResponse
    ) {
        // Update the student
        LOGGER.info("updateStudent(...) - studentId: {}", studentId);
        ... other code ...

        LOGGER.info("Attempting to htmx header responses");
        htmxResponse.setPushUrl("/student/view/"+ studentId );
        htmxResponse.addTrigger("triggerMarkForReview");

        LOGGER.info("htmxResponse pushUrl: {}",htmxResponse.getPushUrl());

        return "student/student-details-info :: student-details-info";
    }
```
I cannot see the htmx related response headers in my browser developer tools.   Thanks in advance.

**Comment by wimdeblauwe** [comment]
Do you have a small reproducer for the issue? Are you using 3.6.3 or 4.0.1?

**Comment by saipanman95** [comment]
I was testing 4.0.1. Let me revert to 3.6.3 and test.

**Comment by saipanman95** [comment]
I didn't catch this before in my logs but now I am running incognito mode with 4.0.1:
```log
2024-12-06T09:19:22.263+10:00  INFO 24198 --- [RecordsManagement] [nio-8080-exec-4] c.m.r.controller.StudentController       : Attempting to htmx header responses
2024-12-06T09:19:22.266+10:00 ERROR 24198 --- [RecordsManagement] [nio-8080-exec-4] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/RecordsManagement] threw exception [Handler processing failed: java.lang.NoSuchMethodError: 'org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod io.github.wimdeblauwe.htmx.spring.boot.mvc.HtmxExceptionHandlerExceptionResolver.getExceptionHandlerMethod(org.springframework.web.method.HandlerMethod, java.lang.Exception)'] with root cause

java.lang.NoSuchMethodError: 'org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod io.github.wimdeblauwe.htmx.spring.boot.mvc.HtmxExceptionHandlerExceptionResolver.getExceptionHandlerMethod(org.springframework.web.method.HandlerMethod, java.lang.Exception)'
	at io.github.wimdeblauwe.htmx.spring.boot.mvc.HtmxExceptionHandlerExceptionResolver.doResolveHandlerMethodException(HtmxExceptionHandlerExceptionResolver.java:29)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:73)
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:182)
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80)
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1357)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1160)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1105)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
```
sorry, I didn't catch the error before in the logs.

3.6.3 works fine passing htmx headers in the response.

**Comment by saipanman95** [comment]
I tried 4.0.0 again no exception thrown but htmx headers not posting in response either.

**Comment by saipanman95** [comment]
@wimdeblauwe I am sorry.  I retested running the application from the terminal and it is working fine.  I am guessing the spring boot developer tools was getting in the way. I appreciate the quick response.  Thank you!
