### ISSUE TITLE
webflux support

### ISSUE THREAD

**Issue by tubbynl** [wimdeblauwe/htmx-spring-boot#24]
i really liked your talk and this concept, it would be even more awesome if this also works with 

```xml
<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
```

in https://developer.okta.com/blog/2022/03/24/thymeleaf-security#create-the-first-controller-class there's an example controller on how to render a template async, it's not really a thing (yet) but good for future support

**Comment by tubbynl** [comment]
it will probably require an webflux alternative to `HtmxMvcConfiguration`

**Comment by netbizltd** [comment]
Regarding htmx-spring-boot (not using thymeleaf but freemarker):

Any workaround for making out-of-band swaps (HtmxResponse) work in reactive Spring Boot?

I found that none of the annotations (@HxRequest, @HxTrigger) work and HtmxResponse throws exception at runtime.
