### ISSUE TITLE
@WebMvcTest needs META-INF configuration

### ISSUE THREAD

**Issue by dsyer** [wimdeblauwe/htmx-spring-boot#77]
There is a `org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureWebMvc.imports` in this project so the tests work here, but it's not in the published jar files so users do not benefit from it. Since it's just a text file we could move it into `src/main/resources` and everyone would be happy?

**Comment by wimdeblauwe** [comment]
Great idea, I have done simliar in my other project [error-handling-spring-boot-starter](https://github.com/wimdeblauwe/error-handling-spring-boot-starter/tree/master/src/main/resources/META-INF/spring)

**Comment by xhaggi** [comment]
@dsyer could you please explain why users benefits from it when no test classes are published in the jar files?

**Comment by xhaggi** [comment]
Ah, of course, I hadn't thought of that.
