### ISSUE TITLE
Unable to find 1.x within maven central

### ISSUE THREAD

**Issue by ccit-spence** [wimdeblauwe/htmx-spring-boot#78]
Trying to test both `htmx-spring-boot` and `htmx-spring-boot-thymleaf`. 

```
        <dependency>
            <groupId>io.github.wimdeblauwe</groupId>
            <artifactId>htmx-spring-boot</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.wimdeblauwe</groupId>
            <artifactId>htmx-spring-boot-thymeleaf</artifactId>
            <version>1.0.0</version>
        </dependency>
```

Results: `Could not find artifact io.github.wimdeblauwe:htmx-spring-boot:pom:1.0.0 in central (https://repo1.maven.org/maven2)`

Spring boot Version 2.7.10, Java 17

**Comment by wimdeblauwe** [comment]
This should work:

```
<dependency>
    <groupId>io.github.wimdeblauwe</groupId>
    <artifactId>htmx-spring-boot-thymeleaf</artifactId>
    <version>1.0.0</version>
</dependency>
```

See https://mvnrepository.com/artifact/io.github.wimdeblauwe/htmx-spring-boot-thymeleaf/1.0.0

The artifact without `thymeleaf` does not exist for Spring Boot 2.x

**Comment by ccit-spence** [comment]
It did, my error was coming from the Thymeleaf related package.  Instead the project was upgraded to Spring 3.  Everything works as expected now.
